name: "Pi Weather Station"
description: "Pi Weather Station directly in your Home Assistant"
version: "1.0.8"
slug: "pws_ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 8080
panel_icon: "mdi:weather-partly-lightning"
panel_title: "Weather Map"
options:
  maps_api_key: ""
  weather_api_key: ""
  geolocation_api_key: ""
  latitude: 0
  longitude: 0
schema:
  maps_api_key: str
  weather_api_key: str
  geolocation_api_key: str
  latitude: float
  longitude: float