name: "Nginx Ingress"
description: "My first real add-on!"
version: "1.0.0"
slug: "nginx_ingress"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: repo/nginx-hass-ingress-{arch}